### ISSUE TITLE
CloudWatch Log Group & KMSKey

### ISSUE THREAD

**Issue by tcheksa62** [aws-cloudformation/aws-cloudformation-resource-schema#119]
Hello,

I got problem when I use this template to deploy KMSKey, KMSAlias and CW LogGroup : 
```yaml
Resources:
  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties: 
      Description: KMS for CloudWatch Log group
      Enabled: true
      KeyPolicy: 
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: '*'
        - Sid: Enable CWL Permissions
          Effect: Allow
          Principal:
            Service: !Sub logs.${AWS::Region}.amazonaws.com
          Action:
          - kms:Describe*
          - kms:Encrypt*
          - kms:Decrypt*
          - kms:ReEncrypt*
          - kms:ReEncrypt*
          Resource: '*'

  KMSAlias:  
    Type: 'AWS::KMS::Alias'
    Properties: 
      AliasName: alias/CloudWatchLogKMS
      TargetKeyId: !Ref KMSKey     
  LogMessage:
    Type: 'AWS::Logs::LogGroup'
    Properties: 
      LogGroupName: /var/log/messages
      RetentionInDays: 365
      KmsKeyId: !Ref KMSKey
```
Error message : 
`Model validation failed (#/KmsKeyId: failed validation constraint for keyword [pattern])`

In the doc of "AWS::KMS::Key" resource, return value is key ID.
But "AWS::Logs::LogGroup" wait an ARN not a KeyID. The param himself if ambiguous "**KmsKeyId**" but in reality is KmsKeyArn

My workaround is to use "Fn::GetAtt" instead of Ref : 
`KmsKeyId: !GetAtt KMSKey.Arn`

Regards,
Tcheksa
